#tworzenie środowiska do kompilacji programu
FROM alpine:3.17 as build-env
RUN apk --update --no-cache add g++
WORKDIR /usr/src/FibCalc
COPY . .
RUN g++ -o FibCalc src/main.cpp

#uruchomienie programu
FROM alpine:3.17
COPY --from=build-env /usr/src/FibCalc /usr/src/FibCalc
WORKDIR /usr/src/FibCalc
CMD ["./FibCalc"]